#mario's states

STAND = "standing"
WALK = "walking"
JUMP = "jumping"
FALL = "falling"
MOV_DEFAULT = 0
MOV_WALK1 = 1
MOV_WALK2 = 2
MOV_WALK3 = 3
MOV_JUMP = 4
MOV_SKID = 5

SIZE_MULTIPLIER = 6
FRICTION_MU = 0.7
BG_MULTIPLIER = 4

SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 900
GROUND_OFFSET = 200