#mario's states

STAND = "standing"
WALK = "walking"
JUMP = "jumping"
FALL = "falling"
MOV_DEFAULT = 0
MOV_WALK1 = 1
MOV_WALK2 = 2
MOV_WALK3 = 3
MOV_JUMP = 4
MOV_SKID = 5

SIZE_MULTIPLIER = 2.5
FRICTION_MU = 0.7
BG_MULTIPLIER = 2.679

SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 600
GROUND_OFFSET = 100
STARTING_POINT_OFFSET = 7